Repository algorithim-leetcode/truffle, pull requests merged in 2024-10, with the labels that each got.

#6 feat: user service 추가
  build.gradle
  src/main/java/com/toy/truffle/global/codeEnum/ResponseStatus.java
  src/main/java/com/toy/truffle/global/dto/CommonResponseDTO.java
  src/main/java/com/toy/truffle/global/util/Argon2PasswordEncryptor.java
  src/main/java/com/toy/truffle/user/dto/RegisterUserDTO.java
  src/main/java/com/toy/truffle/user/service/UserService.java
  src/test/java/com/toy/truffle/global/util/Argon2PasswordEncryptorTest.java
  src/test/java/com/toy/truffle/user/UserRepositoryTest.java
  src/test/java/com/toy/truffle/user/UserServiceTest.java
Labels: feature

#8 feat: 회원가입 컨트롤러 구현
  build.gradle
  src/main/java/com/toy/truffle/user/controller/UserController.java
  src/main/java/com/toy/truffle/user/dto/SignUpDTO.java
  src/main/java/com/toy/truffle/user/service/UserService.java
  src/main/resources/templates/common/login.html
  src/main/resources/templates/common/signUp.html
  src/test/java/com/toy/truffle/user/UserControllerTest.java
  src/test/java/com/toy/truffle/user/UserServiceTest.java
Labels: bug, feature

#9 타임리프 로그인 페이지 추가
  src/main/java/com/toy/truffle/user/controller/UserController.java
  src/main/java/com/toy/truffle/user/dto/SignUpDTO.java
  src/main/resources/templates/common/signUp.html
Labels: feature

#10 TravelMain 테이블 저장 로직 추가
  src/main/java/com/toy/truffle/global/codeEnum/ResponseStatus.java
  src/main/java/com/toy/truffle/travel/controller/TravelController.java
  src/main/java/com/toy/truffle/travel/dto/TravelDto.java
  src/main/java/com/toy/truffle/travel/entity/TravelMain.java
  src/main/java/com/toy/truffle/travel/repository/TravelMainRepository.java
  src/main/java/com/toy/truffle/travel/service/TravelService.java
  src/test/java/com/toy/truffle/travel/TravelControllerTest.java
  src/test/java/com/toy/truffle/travel/TravelMainRepositoryTest.java
  src/test/java/com/toy/truffle/travel/TravelServiceTest.java
Labels: feature

#12 fix: h2 생성 오류 수정
  src/main/java/com/toy/truffle/user/entity/User.java
  src/main/java/com/toy/truffle/user/service/UserService.java
  src/test/java/com/toy/truffle/travel/TravelControllerTest.java
  src/test/java/com/toy/truffle/travel/TravelMainRepositoryTest.java
  src/test/java/com/toy/truffle/travel/TravelServiceTest.java
  src/test/java/com/toy/truffle/user/UserServiceTest.java
Labels: bug, fix

#11 여행지역 저장로직 추가
  src/main/java/com/toy/truffle/destination/dto/DestinationDto.java
  src/main/java/com/toy/truffle/destination/entity/Destination.java
  src/main/java/com/toy/truffle/destination/repository/DestinationRepository.java
  src/main/java/com/toy/truffle/destination/service/DestinationService.java
  src/main/java/com/toy/truffle/global/codeEnum/ResponseStatus.java
  src/main/java/com/toy/truffle/travel/entity/TravelMain.java
  src/test/java/com/toy/truffle/destination/DestinationRepositoryTest.java
  src/test/java/com/toy/truffle/destination/DestinationServiceTest.java
Labels: feature
